# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: init backend
    init: |
      chmod -R 700 *.sh
      cd us-congress-pizza-flag-tracker
      ../update_submodule.sh
      source ./gitpod_init.sh

    command: |
      cd us-congress-pizza-flag-tracker
      ../update_submodule.sh
      source myenv/venv/activate
      ./run.sh
  
  - name: init frontend
    init: |
      chmod -R 700 *.sh
      cd us-congress-pizza-flag-tracker-frontend
      ../update_submodule.sh
      ./gitpod_init.sh

    command: |
      cd us-congress-pizza-flag-tracker-frontend
      ../update_submodule.sh
      npm start

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
  - port: 5000
    onOpen: ignore
    visibility: public
